version: '3'
name: local-user-management-app
services:
  paymentdb:
    image: postgres:12.16
    command: [ "postgres","-c","log_statement=all" ]
    #    restart: always
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '55432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"