INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (4,'Afghanistan ','AF ','AFG ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (8,'Albania ','AL ','ALB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (10,'Antarctica ','AQ ','ATA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (12,'Algeria ','DZ ','DZA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (16,'American Samoa ','AS ','ASM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (20,'Andorra ','AD ','AND ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (24,'Angola ','AO ','AGO ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (28,'Antigua and Barbuda ','AG ','ATG ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (31,'Azerbaijan ','AZ ','AZE ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (32,'Argentina ','AR ','ARG ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (36,'Australia ','AU ','AUS ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (40,'Austria ','AT ','AUT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (44,'Bahamas (the) ','BS ','BHS ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (48,'Bahrain ','BH ','BHR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (50,'Bangladesh ','BD ','BGD ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (51,'Armenia ','AM ','ARM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (52,'Barbados ','BB ','BRB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (56,'Belgium ','BE ','BEL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (60,'Bermuda ','BM ','BMU ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (64,'Bhutan ','BT ','BTN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (68,'Bolivia (Plurinational State of) ','BO ','BOL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (70,'Bosnia and Herzegovina ','BA ','BIH ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (72,'Botswana ','BW ','BWA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (74,'Bouvet Island ','BV ','BVT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (76,'Brazil ','BR ','BRA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (84,'Belize ','BZ ','BLZ ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (86,'British Indian Ocean Territory (the) ','IO ','IOT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (90,'Solomon Islands ','SB ','SLB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (92,'Virgin Islands (British) ','VG ','VGB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (96,'Brunei Darussalam ','BN ','BRN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (100,'Bulgaria ','BG ','BGR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (104,'Myanmar ','MM ','MMR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (108,'Burundi ','BI ','BDI ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (112,'Belarus ','BY ','BLR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (116,'Cambodia ','KH ','KHM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (120,'Cameroon ','CM ','CMR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (124,'Canada ','CA ','CAN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (132,'Cabo Verde ','CV ','CPV ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (136,'Cayman Islands (the) ','KY ','CYM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (140,'Central African Republic (the) ','CF ','CAF ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (144,'Sri Lanka ','LK ','LKA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (148,'Chad ','TD ','TCD ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (152,'Chile ','CL ','CHL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (156,'China ','CN ','CHN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (158,'Taiwan (Province of China) ','TW ','TWN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (162,'Christmas Island ','CX ','CXR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (166,'Cocos (Keeling) Islands (the) ','CC ','CCK ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (170,'Colombia ','CO ','COL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (174,'Comoros (the) ','KM ','COM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (175,'Mayotte ','YT ','MYT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (178,'Congo (the) ','CG ','COG ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (180,'Congo (the Democratic Republic of the) ','CD ','COD ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (184,'Cook Islands (the) ','CK ','COK ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (188,'Costa Rica ','CR ','CRI ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (191,'Croatia ','HR ','HRV ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (192,'Cuba ','CU ','CUB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (196,'Cyprus ','CY ','CYP ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (203,'Czechia ','CZ ','CZE ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (204,'Benin ','BJ ','BEN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (208,'Denmark ','DK ','DNK ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (212,'Dominica ','DM ','DMA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (214,'Dominican Republic (the) ','DO ','DOM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (218,'Ecuador ','EC ','ECU ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (222,'El Salvador ','SV ','SLV ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (226,'Equatorial Guinea ','GQ ','GNQ ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (231,'Ethiopia ','ET ','ETH ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (232,'Eritrea ','ER ','ERI ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (233,'Estonia ','EE ','EST ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (234,'Faroe Islands (the) ','FO ','FRO ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (238,'Falkland Islands (the) [Malvinas] ','FK ','FLK ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (239,'South Georgia and the South Sandwich Islands ','GS ','SGS ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (242,'Fiji ','FJ ','FJI ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (246,'Finland ','FI ','FIN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (248,'Åland Islands ','AX ','ALA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (250,'France ','FR ','FRA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (254,'French Guiana ','GF ','GUF ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (258,'French Polynesia ','PF ','PYF ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (260,'French Southern Territories (the) ','TF ','ATF ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (262,'Djibouti ','DJ ','DJI ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (266,'Gabon ','GA ','GAB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (268,'Georgia ','GE ','GEO ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (270,'Gambia (the) ','GM ','GMB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (275,'Palestine, State of ','PS ','PSE ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (276,'Germany ','DE ','DEU ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (288,'Ghana ','GH ','GHA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (292,'Gibraltar ','GI ','GIB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (296,'Kiribati ','KI ','KIR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (300,'Greece ','GR ','GRC ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (304,'Greenland ','GL ','GRL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (308,'Grenada ','GD ','GRD ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (312,'Guadeloupe ','GP ','GLP ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (316,'Guam ','GU ','GUM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (320,'Guatemala ','GT ','GTM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (324,'Guinea ','GN ','GIN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (328,'Guyana ','GY ','GUY ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (332,'Haiti ','HT ','HTI ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (334,'Heard Island and McDonald Islands ','HM ','HMD ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (336,'Holy See (the) ','VA ','VAT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (340,'Honduras ','HN ','HND ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (344,'Hong Kong ','HK ','HKG ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (348,'Hungary ','HU ','HUN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (352,'Iceland ','IS ','ISL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (356,'India ','IN ','IND ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (360,'Indonesia ','ID ','IDN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (364,'Iran (Islamic Republic of) ','IR ','IRN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (368,'Iraq ','IQ ','IRQ ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (372,'Ireland ','IE ','IRL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (376,'Israel ','IL ','ISR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (380,'Italy ','IT ','ITA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (384,'Côte d''Ivoire ','CI ','CIV ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (388,'Jamaica ','JM ','JAM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (392,'Japan ','JP ','JPN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (398,'Kazakhstan ','KZ ','KAZ ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (400,'Jordan ','JO ','JOR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (404,'Kenya ','KE ','KEN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (408,'Korea (the Democratic People''s Republic of) ','KP ','PRK ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (410,'Korea (the Republic of) ','KR ','KOR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (414,'Kuwait ','KW ','KWT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (417,'Kyrgyzstan ','KG ','KGZ ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (418,'Lao People''s Democratic Republic (the) ','LA ','LAO ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (422,'Lebanon ','LB ','LBN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (426,'Lesotho ','LS ','LSO ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (428,'Latvia ','LV ','LVA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (430,'Liberia ','LR ','LBR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (434,'Libya ','LY ','LBY ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (438,'Liechtenstein ','LI ','LIE ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (440,'Lithuania ','LT ','LTU ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (442,'Luxembourg ','LU ','LUX ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (446,'Macao ','MO ','MAC ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (450,'Madagascar ','MG ','MDG ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (454,'Malawi ','MW ','MWI ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (458,'Malaysia ','MY ','MYS ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (462,'Maldives ','MV ','MDV ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (466,'Mali ','ML ','MLI ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (470,'Malta ','MT ','MLT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (474,'Martinique ','MQ ','MTQ ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (478,'Mauritania ','MR ','MRT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (480,'Mauritius ','MU ','MUS ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (484,'Mexico ','MX ','MEX ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (492,'Monaco ','MC ','MCO ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (496,'Mongolia ','MN ','MNG ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (498,'Moldova (the Republic of) ','MD ','MDA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (499,'Montenegro ','ME ','MNE ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (500,'Montserrat ','MS ','MSR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (504,'Morocco ','MA ','MAR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (508,'Mozambique ','MZ ','MOZ ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (512,'Oman ','OM ','OMN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (516,'Namibia ','NA ','NAM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (520,'Nauru ','NR ','NRU ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (524,'Nepal ','NP ','NPL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (528,'Netherlands (the) ','NL ','NLD ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (531,'Curaçao ','CW ','CUW ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (533,'Aruba ','AW ','ABW ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (534,'Sint Maarten (Dutch part) ','SX ','SXM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (535,'Bonaire, Sint Eustatius and Saba ','BQ ','BES ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (540,'New Caledonia ','NC ','NCL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (548,'Vanuatu ','VU ','VUT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (554,'New Zealand ','NZ ','NZL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (558,'Nicaragua ','NI ','NIC ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (562,'Niger (the) ','NE ','NER ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (566,'Nigeria ','NG ','NGA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (570,'Niue ','NU ','NIU ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (574,'Norfolk Island ','NF ','NFK ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (578,'Norway ','NO ','NOR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (580,'Northern Mariana Islands (the) ','MP ','MNP ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (581,'United States Minor Outlying Islands (the) ','UM ','UMI ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (583,'Micronesia (Federated States of) ','FM ','FSM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (584,'Marshall Islands (the) ','MH ','MHL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (585,'Palau ','PW ','PLW ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (586,'Pakistan ','PK ','PAK ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (591,'Panama ','PA ','PAN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (598,'Papua New Guinea ','PG ','PNG ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (600,'Paraguay ','PY ','PRY ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (604,'Peru ','PE ','PER ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (608,'Philippines (the) ','PH ','PHL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (612,'Pitcairn ','PN ','PCN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (616,'Poland ','PL ','POL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (620,'Portugal ','PT ','PRT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (624,'Guinea-Bissau ','GW ','GNB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (626,'Timor-Leste ','TL ','TLS ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (630,'Puerto Rico ','PR ','PRI ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (634,'Qatar ','QA ','QAT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (638,'Réunion ','RE ','REU ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (642,'Romania ','RO ','ROU ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (643,'Russian Federation (the) ','RU ','RUS ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (646,'Rwanda ','RW ','RWA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (652,'Saint Barthélemy ','BL ','BLM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (654,'Saint Helena, Ascension and Tristan da Cunha ','SH ','SHN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (659,'Saint Kitts and Nevis ','KN ','KNA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (660,'Anguilla ','AI ','AIA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (662,'Saint Lucia ','LC ','LCA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (663,'Saint Martin (French part) ','MF ','MAF ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (666,'Saint Pierre and Miquelon ','PM ','SPM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (670,'Saint Vincent and the Grenadines ','VC ','VCT ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (674,'San Marino ','SM ','SMR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (678,'Sao Tome and Principe ','ST ','STP ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (682,'Saudi Arabia ','SA ','SAU ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (686,'Senegal ','SN ','SEN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (688,'Serbia ','RS ','SRB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (690,'Seychelles ','SC ','SYC ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (694,'Sierra Leone ','SL ','SLE ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (702,'Singapore ','SG ','SGP ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (703,'Slovakia ','SK ','SVK ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (704,'Viet Nam ','VN ','VNM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (705,'Slovenia ','SI ','SVN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (706,'Somalia ','SO ','SOM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (710,'South Africa ','ZA ','ZAF ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (716,'Zimbabwe ','ZW ','ZWE ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (724,'Spain ','ES ','ESP ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (728,'South Sudan ','SS ','SSD ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (729,'Sudan (the) ','SD ','SDN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (732,'Western Sahara ','EH ','ESH ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (740,'Suriname ','SR ','SUR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (744,'Svalbard and Jan Mayen ','SJ ','SJM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (748,'Eswatini ','SZ ','SWZ ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (752,'Sweden ','SE ','SWE ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (756,'Switzerland ','CH ','CHE ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (760,'Syrian Arab Republic ','SY ','SYR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (762,'Tajikistan ','TJ ','TJK ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (764,'Thailand ','TH ','THA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (768,'Togo ','TG ','TGO ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (772,'Tokelau ','TK ','TKL ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (776,'Tonga ','TO ','TON ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (780,'Trinidad and Tobago ','TT ','TTO ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (784,'United Arab Emirates (the) ','AE ','ARE ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (788,'Tunisia ','TN ','TUN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (792,'Turkey ','TR ','TUR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (795,'Turkmenistan ','TM ','TKM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (796,'Turks and Caicos Islands (the) ','TC ','TCA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (798,'Tuvalu ','TV ','TUV ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (800,'Uganda ','UG ','UGA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (804,'Ukraine ','UA ','UKR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (807,'Republic of North Macedonia ','MK ','MKD ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (818,'Egypt ','EG ','EGY ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (826,'United Kingdom of Great Britain and Northern Ireland (the) ','GB ','GBR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (831,'Guernsey ','GG ','GGY ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (832,'Jersey ','JE ','JEY ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (833,'Isle of Man ','IM ','IMN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (834,'Tanzania, United Republic of ','TZ ','TZA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (840,'United States of America (the) ','US ','USA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (850,'Virgin Islands (U.S.) ','VI ','VIR ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (854,'Burkina Faso ','BF ','BFA ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (858,'Uruguay ','UY ','URY ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (860,'Uzbekistan ','UZ ','UZB ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (862,'Venezuela (Bolivarian Republic of) ','VE ','VEN ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (876,'Wallis and Futuna ','WF ','WLF ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (882,'Samoa ','WS ','WSM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (887,'Yemen ','YE ','YEM ','ACTIVE');
INSERT INTO person.countries(id, name, alpha2, alpha3, status) VALUES (894,'Zambia ','ZM ','ZMB ','ACTIVE');